apiVersion: v1
kind: Service
metadata:
  name: gate
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
    - port: 8084
      $patch: delete
    - port: 80
      protocol: TCP
      targetPort: 8084
  # Uncomment below and update IP address range to restrict what IP address can access this service
  # Note that GitHub must be able to reach your gate service: https://docs.github.com/en/github/authenticating-to-github/about-githubs-ip-addresses
  # loadBalancerSourceRanges:
  #   - 192.30.252.0/22
  #   - 185.199.108.0/22
  #   - 140.82.112.0/20
  #   - <yourIP>/32